apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-app-c
  namespace: zeitview
spec:
  podSelector:
    matchLabels:
      app: app-c
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: app-a
    - podSelector:
        matchLabels:
          app: app-b
    ports:
    - protocol: TCP
      port: 80
